### ISSUE TITLE
Usability - No Rank Field present in Add new Member form

### ISSUE THREAD

**Issue by sskarmoutsos** [eaglefox82/moorebankadmin#6]
In the add new member form. there is no field for the User to add Member ran.
This is needed in the case that a pre-existing member is added into the squadron with a previously acquired rank. 

This is also useful for distinguishing cadets from Jr Cadet, Cadet and Sr, Cadet when they join.

**Comment by eaglefox82** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Rank missing when adding a new member](https://trello.com/c/tnWKoK3j/29-rank-missing-when-adding-a-new-member)

**Comment by sskarmoutsos** [comment]
![Rank Missing R2](https://user-images.githubusercontent.com/50933691/58297578-8ad5e080-7e1b-11e9-9793-d72fb5087284.PNG)

The Rank field is still missing the Add new Member form

**Comment by eaglefox82** [comment]
Corrected is now a drop down box. Will be present in release 2
